# Generated by Django 4.0.1 on 2022-02-18 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_blogs_category_contact_menu_slider_tabler_updates_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blogs',
            new_name='Todo',
        ),
    ]
