# Generated by Django 4.0.1 on 2022-02-25 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_blogs_topdishes_delete_todo_slider_bodytext_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='bodyText',
            field=models.TextField(default='Amul the taste of india'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='heading',
            field=models.CharField(default='Indian street food', max_length=200),
        ),
    ]
