# Generated by Django 4.0.1 on 2022-03-16 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_slider_bodytext_alter_slider_heading'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tabler',
            name='dateandtime',
        ),
        migrations.AddField(
            model_name='tabler',
            name='datef',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='tabler',
            name='time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='tabler',
            name='count',
            field=models.IntegerField(default='1'),
        ),
    ]
