# Generated by Django 4.0.1 on 2022-04-15 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_tabler_dateandtime_tabler_datef_tabler_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabler',
            name='count',
            field=models.IntegerField(default='1', null=True),
        ),
    ]
